# version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # depends_on:
      # - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    restart: always
    networks:
      - inception
    depends_on:
      # - wordpress
      - nginx

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   restart: always
      # secrets:
      #  - db_password

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: home/eschussl/data/mariadb
      o: bind
      type: none
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: home/eschussl/data/wordpress
      o: bind
      type: none

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt