services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes: ['wpVol:/var/www/html']
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    restart: always
    networks:
      - inception
    volumes: ['dbVol:/var/lib/mysql']

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes: ['wpVol:/var/www/html']
    env_file:
      - .env
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"

networks:
  inception:
    driver: bridge

volumes:
  dbVol:
    driver: local
    driver_opts:
      device: /home/eschussl/data/dbVol
      o: bind
      type: none
  wpVol:
    driver: local
    driver_opts:
      device: /home/eschussl/data/wpVol
      o: bind
      type: none
