#!/bin/bash

echo "CREATE DATABASE IF NOT EXISTS $WORDPRESS_DB_NAME;
CREATE USER '$WORDPRESS_DB_USER'@'%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD';
GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER'@'%' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY $MYSQL_ROOT_PASSWORD;
FLUSH PRIVILEGES;" > /etc/mysql/init.sql

mysqld